version: '3.4'
services:
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: ../
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"
    environment:
      - MYSQL_HOST=mysql_api
  grpc-server:
      build:
        dockerfile: ./docker/grpc/Dockerfile
        context: ../
      container_name: grpc-server
      ports:
        - "9000:9000"
      networks:
        - prod
      depends_on:
        - "mysql"
        - "redis"
      environment:
        - MYSQL_HOST=mysql_api

  grpc-dev:
    build:
      dockerfile: ./docker/grpc-dev/Dockerfile
      context: ../
    container_name: grpc-dev
    volumes:
      - ../grpc:/go/grpc

  redis:
    image: redis
    container_name: redis
    hostname: redis_api
    networks:
      - prod
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql_api
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856 --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_USER=go_api
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=go_api
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - prod
    expose:
      - '3306'

networks:
  prod:
    driver: bridge