// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentsServiceClient is the client API for StudentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentsServiceClient interface {
	GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error)
	CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error)
	GetStudentById(ctx context.Context, in *GetStudentByIdRequest, opts ...grpc.CallOption) (*GetStudentByIdResponse, error)
	GetStudentByIdWithSubjects(ctx context.Context, in *GetStudentByIdRequest, opts ...grpc.CallOption) (*GetStudentByIdWithSubjectsResponse, error)
	UpdateStudentById(ctx context.Context, in *UpdateStudentByIdRequest, opts ...grpc.CallOption) (*UpdateStudentByIdResponse, error)
	DeleteStudentById(ctx context.Context, in *DeleteStudentByIdRequest, opts ...grpc.CallOption) (*DeleteStudentByIdResponse, error)
}

type studentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentsServiceClient(cc grpc.ClientConnInterface) StudentsServiceClient {
	return &studentsServiceClient{cc}
}

func (c *studentsServiceClient) GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error) {
	out := new(GetStudentsResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/GetStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error) {
	out := new(CreateStudentResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) GetStudentById(ctx context.Context, in *GetStudentByIdRequest, opts ...grpc.CallOption) (*GetStudentByIdResponse, error) {
	out := new(GetStudentByIdResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/GetStudentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) GetStudentByIdWithSubjects(ctx context.Context, in *GetStudentByIdRequest, opts ...grpc.CallOption) (*GetStudentByIdWithSubjectsResponse, error) {
	out := new(GetStudentByIdWithSubjectsResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/GetStudentByIdWithSubjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) UpdateStudentById(ctx context.Context, in *UpdateStudentByIdRequest, opts ...grpc.CallOption) (*UpdateStudentByIdResponse, error) {
	out := new(UpdateStudentByIdResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/UpdateStudentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) DeleteStudentById(ctx context.Context, in *DeleteStudentByIdRequest, opts ...grpc.CallOption) (*DeleteStudentByIdResponse, error) {
	out := new(DeleteStudentByIdResponse)
	err := c.cc.Invoke(ctx, "/grpc.StudentsService/DeleteStudentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentsServiceServer is the server API for StudentsService service.
// All implementations must embed UnimplementedStudentsServiceServer
// for forward compatibility
type StudentsServiceServer interface {
	GetStudents(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error)
	CreateStudent(context.Context, *CreateStudentRequest) (*CreateStudentResponse, error)
	GetStudentById(context.Context, *GetStudentByIdRequest) (*GetStudentByIdResponse, error)
	GetStudentByIdWithSubjects(context.Context, *GetStudentByIdRequest) (*GetStudentByIdWithSubjectsResponse, error)
	UpdateStudentById(context.Context, *UpdateStudentByIdRequest) (*UpdateStudentByIdResponse, error)
	DeleteStudentById(context.Context, *DeleteStudentByIdRequest) (*DeleteStudentByIdResponse, error)
	mustEmbedUnimplementedStudentsServiceServer()
}

// UnimplementedStudentsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudentsServiceServer struct {
}

func (UnimplementedStudentsServiceServer) GetStudents(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}
func (UnimplementedStudentsServiceServer) CreateStudent(context.Context, *CreateStudentRequest) (*CreateStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudent not implemented")
}
func (UnimplementedStudentsServiceServer) GetStudentById(context.Context, *GetStudentByIdRequest) (*GetStudentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentById not implemented")
}
func (UnimplementedStudentsServiceServer) GetStudentByIdWithSubjects(context.Context, *GetStudentByIdRequest) (*GetStudentByIdWithSubjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentByIdWithSubjects not implemented")
}
func (UnimplementedStudentsServiceServer) UpdateStudentById(context.Context, *UpdateStudentByIdRequest) (*UpdateStudentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudentById not implemented")
}
func (UnimplementedStudentsServiceServer) DeleteStudentById(context.Context, *DeleteStudentByIdRequest) (*DeleteStudentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudentById not implemented")
}
func (UnimplementedStudentsServiceServer) mustEmbedUnimplementedStudentsServiceServer() {}

// UnsafeStudentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentsServiceServer will
// result in compilation errors.
type UnsafeStudentsServiceServer interface {
	mustEmbedUnimplementedStudentsServiceServer()
}

func RegisterStudentsServiceServer(s grpc.ServiceRegistrar, srv StudentsServiceServer) {
	s.RegisterService(&StudentsService_ServiceDesc, srv)
}

func _StudentsService_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/GetStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).GetStudents(ctx, req.(*GetStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).CreateStudent(ctx, req.(*CreateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_GetStudentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).GetStudentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/GetStudentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).GetStudentById(ctx, req.(*GetStudentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_GetStudentByIdWithSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).GetStudentByIdWithSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/GetStudentByIdWithSubjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).GetStudentByIdWithSubjects(ctx, req.(*GetStudentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_UpdateStudentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).UpdateStudentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/UpdateStudentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).UpdateStudentById(ctx, req.(*UpdateStudentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_DeleteStudentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).DeleteStudentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StudentsService/DeleteStudentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).DeleteStudentById(ctx, req.(*DeleteStudentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentsService_ServiceDesc is the grpc.ServiceDesc for StudentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.StudentsService",
	HandlerType: (*StudentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudents",
			Handler:    _StudentsService_GetStudents_Handler,
		},
		{
			MethodName: "CreateStudent",
			Handler:    _StudentsService_CreateStudent_Handler,
		},
		{
			MethodName: "GetStudentById",
			Handler:    _StudentsService_GetStudentById_Handler,
		},
		{
			MethodName: "GetStudentByIdWithSubjects",
			Handler:    _StudentsService_GetStudentByIdWithSubjects_Handler,
		},
		{
			MethodName: "UpdateStudentById",
			Handler:    _StudentsService_UpdateStudentById_Handler,
		},
		{
			MethodName: "DeleteStudentById",
			Handler:    _StudentsService_DeleteStudentById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "students.proto",
}
